#:schema node_modules/wrangler/config-schema.json
name = "solditor"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

[env.production]
# Production environment variables
# Set these in your Cloudflare dashboard

[env.preview]
# Staging environment variables
